import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface CandidateData {
    name: string;
    score: number;
}

export const generateEvaluationPDF = (candidate: CandidateData) => {
    const doc = new jsPDF();
    const { name, score } = candidate;

    // Colors
    const ORANGE = '#f97316';
    const BLACK = '#000000';
    const GRAY = '#4b5563';

    // Header Background
    doc.setFillColor(ORANGE);
    doc.rect(0, 0, 210, 40, 'F');

    // Title
    doc.setTextColor('#ffffff');
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text("SkillSphere Evaluation Report", 20, 25);

    // Candidate Info
    doc.setTextColor(BLACK);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(`Candidate: ${name}`, 20, 60);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 70);

    // Score Section
    doc.setDrawColor(ORANGE);
    doc.setLineWidth(1);
    doc.rect(20, 85, 170, 40); // Box

    doc.setFontSize(14);
    doc.setTextColor(GRAY);
    doc.text("Overall Performance Score", 105, 100, { align: 'center' });

    doc.setFontSize(30);
    doc.setTextColor(ORANGE);
    doc.setFont('helvetica', 'bold');
    doc.text(`${score} / 1000`, 105, 115, { align: 'center' });

    // Evaluation Details (Simulation based on score logic from modal)
    const isHighPerformer = score > 800;

    const strengths = isHighPerformer
        ? ["Excellent problem decomposition skills.", "Strong grasp of time complexity analysis.", "Clear and professional communication."]
        : ["Good attempt at identifying edge cases.", "Demonstrated persistence in debugging.", "Basic understanding of data structures."];

    const weaknesses = isHighPerformer
        ? ["Could optimize space complexity further.", "Minor syntax hesitations in corner cases."]
        : ["Struggled with optimal solution derivation.", "Communication could be more structured.", "Code modularity needs improvement."];

    // Strengths Table
    autoTable(doc, {
        startY: 140,
        head: [['Key Strengths']],
        body: strengths.map(s => [s]),
        theme: 'grid',
        headStyles: { fillColor: [34, 197, 94], textColor: 255, fontStyle: 'bold' }, // Green
        styles: { fontSize: 11, cellPadding: 5 },
    });

    // Weaknesses Table
    // @ts-ignore - autoTable adds lastAutoTable to doc
    const finalY = doc.lastAutoTable.finalY + 15;

    autoTable(doc, {
        startY: finalY,
        head: [['Areas for Improvement']],
        body: weaknesses.map(w => [w]),
        theme: 'grid',
        headStyles: { fillColor: [249, 115, 22], textColor: 255, fontStyle: 'bold' }, // Orange
        styles: { fontSize: 11, cellPadding: 5 },
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(GRAY);
    doc.text("Generated by SkillSphere AI • Automated Assessment System", 105, 280, { align: 'center' });

    // Save
    doc.save(`${name.replace(/\s+/g, '_')}_Evaluation_Report.pdf`);
};
